version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - FLASK_ENV=development
    depends_on:
      - qdrant
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
